server:
  port: 8081

spring:
  application:
    name: resume

  datasource:
    url: jdbc:mysql://localhost:3306/practicedb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${BREVO_USERNAME}
    password: ${BREVO_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp
    default-encoding: UTF-8

# Logging Configuration
logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG

# =====================
# Custom App Properties
# =====================
app:
  email:
    from: manishk57107@gmail.com
    verification-link-expiry-hours: 24

  base:
    url: http://localhost:8081

# =====================
# Cloudinary Configuration
# =====================
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  secure: true

# =====================
# JWT Configuration
# =====================
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

# =====================
# Razorpay Configuration
# =====================
razorpay:
  key-id: ${RAZORPAY_KEY_ID}
  key-secret: ${RAZORPAY_KEY_SECRET}
  currency: INR
  payment-capture: true   # auto-capture payment after authorization
